/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DeviceManager */

#ifndef _Included_DeviceManagerService
#define _Included_DeviceManagerService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xxdroid_idevice_DeviceManager
 * Method:    getDeviceListNative
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_xxdroid_idevice_DeviceManagerService_getDeviceListNative
  (JNIEnv *, jobject);

/*
 * Class:     com_xxdroid_idevice_DeviceManager
 * Method:    getDeviceInfoNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xxdroid_idevice_DeviceManagerService_getDeviceInfoNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
